import type { CardStyle } from '../api';

/**
 * Normalizes optional card style attributes to sane defaults so consuming
 * components can rely on consistent class names.
 */
export const applyDefaultCardStyleValues = (style: CardStyle): CardStyle => ({
  ...style,
  front_title_background_color: style.front_title_background_color || 'bg-white',
  front_title_border_color: style.front_title_border_color || 'none',
  front_title_border_width: style.front_title_border_width || 'border',
  front_content_size: style.front_content_size || 'text-sm',
  front_content_color: style.front_content_color || 'text-slate-900',
  front_content_align: style.front_content_align || 'text-left',
  front_content_margin_top: style.front_content_margin_top || '0',
  front_content_margin_bottom: style.front_content_margin_bottom || '0',
  front_content_margin_left: style.front_content_margin_left || '0',
  front_content_margin_right: style.front_content_margin_right || '0',
  mcq_option_background_color: style.mcq_option_background_color || 'bg-white',
  mcq_option_border_color: style.mcq_option_border_color || 'none',
  mcq_option_border_width: style.mcq_option_border_width || 'border',
  mcq_option_gap: style.mcq_option_gap || '8',
  short_input_height: style.short_input_height || 'h-12',
  short_input_background_color: style.short_input_background_color || 'bg-white',
  short_input_border_color: style.short_input_border_color || 'border-slate-300',
  short_input_border_width: style.short_input_border_width || 'border',
  short_button_size: style.short_button_size || 'px-4 py-2',
  short_button_color: style.short_button_color || 'bg-primary-600 text-white',
  short_button_font_size: style.short_button_font_size || 'text-sm',
  ox_button_o_size: style.ox_button_o_size || 'h-20 w-20 text-xl',
  ox_button_o_background_color: style.ox_button_o_background_color || 'bg-emerald-700 text-white',
  ox_button_o_radius: style.ox_button_o_radius || 'rounded-full',
  ox_button_o_border_color: style.ox_button_o_border_color || 'none',
  ox_button_o_border_width: style.ox_button_o_border_width || 'border',
  ox_button_x_size: style.ox_button_x_size || 'h-20 w-20 text-xl',
  ox_button_x_background_color: style.ox_button_x_background_color || 'bg-rose-700 text-white',
  ox_button_x_radius: style.ox_button_x_radius || 'rounded-full',
  ox_button_x_border_color: style.ox_button_x_border_color || 'none',
  ox_button_x_border_width: style.ox_button_x_border_width || 'border',
  ox_button_gap: style.ox_button_gap || '24',
  cloze_text_font_size: style.cloze_text_font_size || 'text-base',
  cloze_text_align: style.cloze_text_align || 'justify-center',
  cloze_text_background_color: style.cloze_text_background_color || 'bg-transparent',
  cloze_text_border_color: style.cloze_text_border_color || 'none',
  cloze_text_border_width: style.cloze_text_border_width || 'border',
  cloze_input_font_size: style.cloze_input_font_size || 'text-base',
  cloze_input_background_color: style.cloze_input_background_color || 'bg-transparent',
  cloze_input_border_color: style.cloze_input_border_color || 'border-primary-500',
  cloze_input_border_width: style.cloze_input_border_width || 'border-b',
  cloze_input_underline_color: style.cloze_input_underline_color || 'focus:border-primary-500',
  cloze_button_size: style.cloze_button_size || 'px-4 py-2',
  cloze_button_color: style.cloze_button_color || 'bg-primary-600 text-white',
  cloze_button_font_size: style.cloze_button_font_size || 'text-sm',
  order_item_background_color: style.order_item_background_color || 'bg-white',
  order_item_border_color: style.order_item_border_color || 'border-slate-300',
  order_item_border_width: style.order_item_border_width || 'border',
  order_item_gap: style.order_item_gap || '8',
  order_button_size: style.order_button_size || 'px-4 py-2',
  order_button_color: style.order_button_color || 'bg-primary-600 text-white',
  order_button_font_size: style.order_button_font_size || 'text-sm',
  order_guide_align: style.order_guide_align || 'text-left',
  order_guide_font_size: style.order_guide_font_size || 'text-xs',
  order_guide_background_color: style.order_guide_background_color || 'bg-transparent',
  order_guide_border_color: style.order_guide_border_color || 'none',
  order_guide_border_width: style.order_guide_border_width || 'border',
  match_item_background_color: style.match_item_background_color || 'bg-white',
  match_item_border_color: style.match_item_border_color || 'border-slate-200',
  match_item_border_width: style.match_item_border_width || 'border',
  match_item_1_background_color: style.match_item_1_background_color || 'bg-white',
  match_item_1_border_color: style.match_item_1_border_color || 'border-slate-200',
  match_item_1_border_width: style.match_item_1_border_width || 'border',
  match_item_1_font_size: style.match_item_1_font_size || 'text-sm',
  match_item_1_text_align: style.match_item_1_text_align || 'text-left',
  match_item_2_background_color: style.match_item_2_background_color || 'bg-white',
  match_item_2_border_color: style.match_item_2_border_color || 'border-slate-200',
  match_item_2_border_width: style.match_item_2_border_width || 'border',
  match_item_2_font_size: style.match_item_2_font_size || 'text-sm',
  match_item_2_text_align: style.match_item_2_text_align || 'text-left',
  match_item_3_background_color: style.match_item_3_background_color || 'bg-white',
  match_item_3_border_color: style.match_item_3_border_color || 'border-slate-200',
  match_item_3_border_width: style.match_item_3_border_width || 'border',
  match_item_3_font_size: style.match_item_3_font_size || 'text-sm',
  match_item_3_text_align: style.match_item_3_text_align || 'text-left',
  match_item_4_background_color: style.match_item_4_background_color || 'bg-white',
  match_item_4_border_color: style.match_item_4_border_color || 'border-slate-200',
  match_item_4_border_width: style.match_item_4_border_width || 'border',
  match_item_4_font_size: style.match_item_4_font_size || 'text-sm',
  match_item_4_text_align: style.match_item_4_text_align || 'text-left',
  match_item_gap: style.match_item_gap || '8',
  match_line_color: style.match_line_color || 'default',
  match_button_size: style.match_button_size || 'px-4 py-2',
  match_button_color: style.match_button_color || 'bg-primary-600 text-white',
  match_button_font_size: style.match_button_font_size || 'text-sm',
  match_guide_align: style.match_guide_align || 'text-left',
  match_guide_font_size: style.match_guide_font_size || 'text-xs',
  match_guide_background_color: style.match_guide_background_color || 'bg-transparent',
  match_guide_border_color: style.match_guide_border_color || 'none',
  match_guide_border_width: style.match_guide_border_width || 'border',
});

